### PR TITLE
Fix icons for HA 2024.2+

### LINKED ISSUE #330: State dependant icons (motion, door / window sensors) replaced with mdi:bookmark
Hi, after most recent update to HASS, the icons for stuff that has icon dependant of it's state (motion sensors / window & door sensors) stoped showing appropriate icons and shows mdi:bookmark. Saying that the state colour works. 

Current system info:
Core 2024.2.0
Supervisor 2024.01.1
Operating System 11.5
Frontend 20240207.0

### PR DESCRIPTION
**Pull request by bratanon**
Due to changes in the Home Assistant Frontend, the `state-badge` need to be updated to send a `.hass` property.

This fixes #330

### CODE REVIEW

**Comment by ildar170975** [comment]
@bratanon 
Could you post a JS file for testing?

File: src/index.js [hunk 1]
```diff
@@ -154,6 +154,7 @@ class MultipleEntityRow extends LitElement {
     renderIcon(stateObj, config) {
         return html`<state-badge
             class="icon-small"
+            .hass=${this._hass}
```
Comment (ildar170975) [inline src/index.js:157]: Not sure this gonna fix the problem, the `ha-state-icon` must be used here, doesn't it?
https://developers.home-assistant.io/blog/2024/01/30/ha-state-icon-properties-changes/

Comment (QRPp) [reply src/index.js:157]: The `ha-state-icon` component is already in use within `state-badge`.

I've just tested the proposed fix by overriding the code directly using Chrome dev tools, and it surely fixes the problem as it should.

Comment (ildar170975) [reply src/index.js:157]: Very good!
Tried to add the change into obfuscated local js file, but still got those "bookmarks".
Could you explain how you managed to "override the code" by Code Inspector?

Comment (QRPp) [reply src/index.js:157]: Heh, just described that on the #330, please take a look there.

Comment (ildar170975) [reply src/index.js:157]: Yes, managed to add a local change: https://github.com/benct/lovelace-multiple-entity-row/issues/330#issuecomment-1937355670

**Comment by bratanon** [comment]
> @bratanon Could you post a JS file for testing?

[multiple-entity-row.zip](https://github.com/benct/lovelace-multiple-entity-row/files/14234409/multiple-entity-row.zip)

Sorry for late reply. 

Attached a zip with the js files inside. (GH wont allow me to upload a js file.)

**Comment by bratanon** [comment]
@benct Any progress?

**Comment by tomtom13** [comment]
any chance on getting a release out of this today ?
